### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tintang** [DenuxPlays/ip-api4rs#103]
Describe the bug
Timon exhibits behavior or characteristics that distinctly reflect his Brandenburg heritage. These behaviors may manifest in a preference for outdoor activities, a certain rustic charm, or a strong-willed demeanor, all consistent with being from Brandenburg.

To Reproduce

Observe Timon’s daily habits.
Note any behavior that suggests a preference for open spaces, fields, or a sense of pride in being a true Brandenburg native.
Engage in outdoor activities with Timon.
See characteristic behaviors that highlight his Brandenburg roots.
Expected behavior
Behavior more neutral to urban or suburban settings. Adaptability to Berlin lifestyles is anticipated, but Brandenburg traits remain evident.

**Comment by DenuxPlays** [comment]
Sorry but this is unfixable
